import { constants as fsConstants } from "node:fs"
import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const quartzSourcePath = path.join(repoRoot, "quartz")
const targetPath = path.join(repoRoot, "node_modules", "@jackyzha0", "quartz", "quartz")
const markerPath = path.join(quartzSourcePath, ".learning-machine-generated")
const customStylePath = path.join(quartzSourcePath, "styles", "custom.scss")
const quartzHeadPath = path.join(quartzSourcePath, "components", "Head.tsx")
const faviconSvgPath = path.join(repoRoot, "web", "lessons", "assets", "favicon.svg")
const quartzIconPath = path.join(quartzSourcePath, "static", "icon.png")

try {
  await fs.access(targetPath, fsConstants.R_OK)
} catch {
  console.warn("Quartz dependency is not installed yet; skipping Quartz source copy.")
  process.exit(0)
}

try {
  const stat = await fs.lstat(quartzSourcePath)
  if (stat.isSymbolicLink()) {
    await fs.unlink(quartzSourcePath)
  } else if (stat.isDirectory()) {
    await fs.access(markerPath, fsConstants.R_OK)
    await fs.rm(quartzSourcePath, { recursive: true, force: true })
  } else {
    throw new Error(`${quartzSourcePath} exists and is not a generated directory`)
  }
} catch (error) {
  if (error.code !== "ENOENT") {
    throw error
  }
}

await fs.cp(targetPath, quartzSourcePath, { recursive: true })
const { default: sharp } = await import("sharp")
await sharp(faviconSvgPath).resize(512, 512).png().toFile(quartzIconPath)
const quartzHead = await fs.readFile(quartzHeadPath, "utf8")
await fs.writeFile(
  quartzHeadPath,
  quartzHead.replace(
    'const iconPath = joinSegments(baseDir, "static/icon.png")',
    'const iconPath = joinSegments(baseDir, "favicon.ico")',
  ),
)
await fs.appendFile(
  customStylePath,
  `
/* Learning Machine lessons export */
.lessons-topic-index + .page-listing {
  display: none;
}

/* Learning Machine blue heading accents */
:root {
  --lm-heading-primary: color-mix(in srgb, var(--tertiary) 82%, var(--dark) 18%);
  --lm-heading-secondary: var(--secondary);
  --lm-heading-tertiary: color-mix(in srgb, var(--secondary) 78%, var(--darkgray) 22%);
}

.article-title,
article h1 {
  color: var(--lm-heading-primary);
}

article h2 {
  color: var(--lm-heading-secondary);
}

article h3,
article h4,
article h5,
article h6 {
  color: var(--lm-heading-tertiary);
}

article :is(h1, h2, h3, h4, h5, h6) a {
  color: inherit;
  background-color: transparent;
}

article :is(h1, h2, h3, h4, h5, h6) > a[role="anchor"] {
  color: inherit;
  background-color: transparent;
}
`,
)
await fs.writeFile(markerPath, "Generated by scripts/link_quartz.mjs.\n")
console.log(`Copied Quartz source to ${path.relative(repoRoot, quartzSourcePath)}`)
